### ISSUE TITLE
HTML and CSS

### ISSUE THREAD

**Issue by adamgmcfadden** [adamgmcfadden/codeQuiz#1]
## Description
-Need static webpage before js can be implemented

-Create HTML tree with logical elements and classes
-Style with CSS
-Should resemble mock-up page when done

**Comment by skpandey885** [comment]
hey! can I work on it?

**Comment by adamgmcfadden** [comment]
> hey! can I work on it?

Hi, thank you for offering. I'm a student, and they've  been teaching us to create these issues to organize a logical structure to building our apps/websites. I really not looking for any help on this as it's a graded assignment.

Thanks again.
